### PR TITLE
Fix issue 7 (!)

### PR DESCRIPTION
**Pull request by za419**
Finally, after so very long (312 days), the volume bar shall no longer look like trash on Android Firefox.

RIP, #7. You, frankly, probably won't be missed. But the memes we could make about you, those, we most definitely will.

@kenellorando I swear to *deity here*, we just memed about this, if you copy-paste this without merging the damn PR.........

### CODE REVIEW

**Comment by za419** [comment]
This is what the page looked like on my phone on March 29th, showing this bug on the now-defunct Space Station theme:

screenshot_2017-03-29-00-18-41

This is what the page looks like with `volume-bar.css` from this PR loaded into the page, showing a lack of this bug on `chicago-evening`:

screenshot_20180110-023421

**Comment by za419** [comment]
Note that I did switch from a Galaxy S4 running Lollipop (5.0.1) to a Galaxy S8 running Nougat (7.0) in the interim. That's the source of some of the differences, perhaps most notably the navigation bar with battery display at the bottom. Additionally, Firefox has been updated a lot, as has Cadence (there's a search bar for song requests!!), so there are a good number of differences there as well.

**Comment by za419** [comment]
@kenellorando sees....

**Comment by za419** [comment]
very interesting....

**Comment by za419** [comment]
HMMMMMMMMMMM

**Comment by kenellorando** [comment]
On second thought, perhaps the trash volume bar was not so trash after all in the end...

**Comment by za419** [comment]
I dunno, @kenellorando, that's the same volume bar on Chrome....

Maybe we should just rework the whole thing?

**Comment by kenellorando** [comment]
nah. good job.

**Comment by za419** [comment]
thanks, @kenellorando

**Comment by kenellorando** [comment]
issue 7

F

**Comment by za419** [comment]
F

**Comment by za419** [comment]
[F](https://github.com/kenellorando/cadence/commit/44cfedaaf7ae400c80999ff31507a6a9300dda66)

[F](https://github.com/kenellorando/cadence/commit/e6262038605eee83acd4535c65257d57228fb718)

**Comment by za419** [comment]
Also, while we're at it....

RIP Space Station March 28th 2017 (according to announcement) - [March 31 2017](https://github.com/kenellorando/cadence/commit/ae4bb13c8356f2243af9d873ad6537f78329e259). You had a short life, we hardly knew you, but you have been missed.

**Pull request merged**
