### PR TITLE
Randomize cyberpunk bartender background

### PR DESCRIPTION
**Pull request by za419**
I had fun

As a side note... It seems that @kenellorando performed a rebase or something, followed by a force-push, and caused our entire history to diverge. I practically had a heart attack when I saw that. I know how to restore his master, but @kenellorando need to talk.

### CODE REVIEW

**Comment by kenellorando** [comment]
force push


Seriously though, I was checking to see if I could reauthor the commits I made under just the name "Ken Ellorando" to actually count to github contributions. Thought I ran an abort command but guess I got work to do

**Comment by za419** [comment]
Lol. It would probably be easier to register that email with github so it knows its you

**Comment by kenellorando** [comment]
Problem is, there may not have been an email at all, the only two emails I've used in the last few years are already registered with this github account.

**Comment by za419** [comment]
Wut... Uh

**Comment by za419** [comment]
Well, you should mark an email for yourself in git.... 

Out of curiosity, although I don't think this will work, can you mark "Ken Ellorando" as an email? That's what git puts where it usually puts emails for me

**Comment by kenellorando** [comment]
Doesn't look like I can add "Ken Ellorando" on github. Something something not a proper email

**Comment by za419** [comment]
Thought so. Damn

**Comment by za419** [comment]
@kenellorando should tell me if he likes this, so I can start work on that 'City' theme we discussed

**Comment by za419** [comment]
Oh, and in case you're wondering....

[This](https://www.youtube.com/watch?v=0NWLIE9eOpE) is what this branch looks like, as of 1ca4cc2

**Comment by za419** [comment]
@kenellorando will look at this someday...
image

Maybe not today, but someday... 
image

Oh yes, maybe someday.... 
image

That legendary someday.... 
image

Does anyone know when that is?

**Comment by za419** [comment]
In order to make this PR better fit the new feature in 03befd700a09e81e788a8821c0aa34c8d888d61f, I disabled the background switching while the theme is in night mode (I figured the white flashes performed during transition would be, uhh, distracting, to say the least).

Additionally, the nighttime background added in the same commit is intentionally left out of the array of cyberpunk backgrounds - I thought it would be weird to switch to it randomly during the day. @kenellorando can of course add it back in if he'd like.

Assuming, that is, that he ever looks at a PR that's approaching two months of age. EVER. No passive aggression over here... No salt either.

**Comment by za419** [comment]
daMMIT @kenellorando STOP BREAKING MY PULL REQUESTS AND MERGE THEM ALREADY

**Comment by za419** [comment]
The old "callback" present here was a pale shadow of, and a grandparent of, the callback interface presented in #111. It has thus been removed, and the old switcher code has been adapted to fit the callback system in #111.

This PR therefore depends on #111, and merging this now implies merging that (although it would be nice to let GitHub know about it).

**Comment by za419** [comment]
Once more, here I say....

> As a side note... It seems that @kenellorando performed a rebase or something, followed by a force-push, and caused our entire history to diverge. I practically had a heart attack when I saw that. I know how to restore his master, but @kenellorando need to talk.

That's right folks! This pull request is so old, it's now survived @kenellorando changing and force-pushing the entire history of Cadence, twice!

image

**Comment by za419** [comment]
Note that some of these diffs are... very bad. Nothing like what they were originally. Some commits have been left out entirely. The commits are mostly kept so that some of the history of this development can be retained.

The diff at large for this pull request, however, is correct.

That is to say, commits through all of this should not be relied on as preserving the *contents* of history, just the framework, but the request still does its task because I've ensured that the total diff does the job.

**Comment by za419** [comment]
Wow savage. Ended up not liking it, all these months down the road?

**Comment by za419** [comment]
@kenellorando .....

**Comment by kenellorando** [comment]
Goodnight, sweet prince

**Pull request closed without merging**
