### PR TITLE
Resurrect Space Station

### PR DESCRIPTION
**Pull request by za419**
This pull request brings the long-gone Space Station theme back.

Space Station was the first video theme on Cadence, and how it was developed provided architecture work for the current `light-mage` theme. It was also the third theme implemented for Cadence.

It had a very short life of about four days. @kenellorando removed it for being too resource-heavy on mobile devices. This was a very fair removal, and it is inarguable simply be diffing f434441c5fa1a67722c15b4c200b4fde0be60857 (the last common ancestor between `master` and my archival `space-station` branch) and 0370839ead67ff7daf1a0e4550c1fc5c485eab41 (almost five hundred commits in between) that after doing so we have made incredible progress - We have working and highly reliable song requests! We even have a Discord bot hooking into those song requests!

However. Space Station was a very nice theme. On desktop, where it didn't matter how excessive its resource usage was, it was a beautiful theme, and a nice contribution to Cadence's array of themes (in my opinion).

Of course, over four hundred commits lead for a long time to Space Station being un-revivable. Notably, for a very long time, my placeholder nightmode detection code switched the theme every ten seconds, which produced interference with Space Station. The fix for `light-mage` would of course apply to this, so the issue didn't quite persist until 637b61d6f7bfc2e6f7c0b6b9e593bc4a3fa59167.

The biggest issue has remained the simple fact that Space Station is a very heavy theme, and lower end mobile devices handled it extremely poorly, and even on high end devices it was unacceptably heavy (especially on the network), and never really looked *good*.

Here, I'm resurrecting Space Station as `space-station`, a modern theme for the modern theme engine, with an extension to the theme system: Themes may now specify that they may not be loaded on mobile, and may either choose to be defaulted on mobile (to `chicago-evening`) or may specify a theme to be loaded instead of themselves on mobile. As part of this, I added a new `earth` theme, which `space-station` marks as its chosen replacement on mobile.

Therefore, `space-station` will no longer have resource problems on mobile (as it cannot be loaded on mobile), and can return to the desktop.

In order to keep the repository size down, and avoid the events of the last set of work on Space Station (which inflated the `.git` folder for Cadence to over 150MB), this pull request re-introduces `git-lfs`. I introduced this near the end of the life of Space Station in an attempt to halt the rapid growth of the `.git` folder, but it was removed at the same time @kenellorando removed Space Station, and not re-introduced for the very small `light-mage`.

However, the new, soundless `iss.mp4` is still almost 40MB. So it needs to be in LFS.

Therefore, @kenellorando, before pulling these commits to a local machine, you need to make sure LFS is installed (or else this PR will not work and possibly break `light-mage`). If it isn't, or if you aren't sure:

1. Download LFS from [here](https://git-lfs.github.com/).
2. Run `git lfs install` in the Cadence repository.
3. Now, pull as normal and confirm that `iss.mp4` is a video (instead of a three-line text file).

As part of this pull request, #36 will be merged, adding a note in the README explaining that in order to properly clone Cadence, you must install LFS.

### CODE REVIEW

**Comment by za419** [comment]
The added themes look like this on my machine.

`earth`:

image

`space-station`:

image

Note that `space-station` received stronger text shadows since I took that screenshot (in order to enhance legibility even further), but is otherwise the same.

**Comment by za419** [comment]
I wasn't really able to test `earth` on mobile, so it will be necessary to test it on mobile after this is merged. I hereby volunteer for the task, but I really do need @kenellorando to merge this to let me do that.

**Comment by za419** [comment]
Why did GitHub make me fix the same merge conflicts twice in consecutive commits? That's a good question, I don't know the answer to that question.

**Comment by za419** [comment]
Why did GitHub make me fix the same merge conflicts twice in consecutive commits? That's a good question, I don't know the answer to that question.

**Comment by kenellorando** [comment]
Nj

**Pull request merged**
