### PR TITLE
Project "WDJDIHFT"

### PR DESCRIPTION
**Pull request by magix430**
what does jakob do in his free time

### CODE REVIEW

**Comment by JakobFrank** [comment]
To be fair, the note says that I contributed toward media, which I did. Therefore, this pull request really doesn't make much sense.

**Comment by magix430** [comment]
We will see

Best,
Kelvin

**Comment by magix430** [comment]
Wait this was in May? Wow memes die fast.

**Comment by za419** [comment]
You think that's a long time?

See #40

**Comment by kenellorando** [comment]
Jakob does the following in his free time:
- Play league
- Play hearthstone
- Listen to music

**Pull request closed without merging**
