### PR TITLE
Add rotating variant of nebula theme

### PR DESCRIPTION
**Pull request by za419**
This theme concept was created by @Karenwithakay .

The media for this theme is a full rotation of the media for the standard `nebula` theme in four minutes. With the exception of having this video background, the theme is identical to the standard `nebula` theme.

In order to best balance quality and bandwidth requirements, two separate videos are used (following the old `iss.mp4`/`iss-mobile.mp4`). On desktop, a 1080p, 60 frames-per-second video, encoded at a high constant quality, is used to ensure high media quality. On mobile, a downscaled 720p, 30 frames-per-second video, encoded at a lower quality setting, is used to ensure good behavior over mobile networks - The mobile version is only 18MB.

Both files were encoded using FFmpeg, via libx264. Full details of their encoder settings can be found in the messages for the commits which introduced them, respectively f497fe2 and fb251b9.

### CODE REVIEW

**Comment by za419** [comment]
Temporarily, I'll be running a VM with a version of Cadence which uses this theme by default (and can load it in later with the "TEST" theme selection), so it can be viewed live, free of YouTube compression (this will continue until the pullrequest is closed or I need the VM for something else).

You can view it [here.](http://ec2-18-224-65-64.us-east-2.compute.amazonaws.com/)

**Comment by za419** [comment]
The uncropped 'master' output of these two videos is very large. I currently have it in two formats:

 - An 87 GB folder of PNG files (the original output from the render)
 - A 55 GB Matroska video encoded losslessly in FFV1 (the proximal master used to produce these outputs)

If @kenellorando wants either of these, we can negotiate on how they can be transferred. On the other hand, I've been considering the production of an h.265 HEVC `pseudomaster`, which can either be nearly-lossless (encoded with very high quality), or a very complex lossless encode, and should be around 5GB. Would anyone like a master copy?

**Comment by za419** [comment]
Don't approve?

**Comment by kenellorando** [comment]
Lets have a discord call

**Pull request merged**
