### PR TITLE
Add creepy cadence theme

### PR DESCRIPTION
**Pull request by za419**
This theme was born out of a desire to make @karenwithakay uncomfortable.

No, seriously, I was showing her around `theme.json` and she mentioned how creepy it would be to have a theme with a lowercase title and uppercased body, and then how creepy it would be if the title glitched to being capitalized, then to being misspelled, and it all pretty much snowballed from there.

And now its a theme. A pretty neat one, if I do say so.

*****

Questions:

@kenellorando, should we switch the name of it? I dunno, Creepy Cadence sounds boring, but that's probably because I've been using it as an indev name.

Also, should we enable `blockMobile`? This isn't as bad as `space-station`, but it's running a *lot* of CSS animations constantly, it could be a battery drainer.

*****

Between @kenellorando , @karenwithakay, and I, we've been discussing the implementation of a mechanism to have `defaultTheme` load this theme by default on, for example, Halloween. While we've agreed that this would be a neat feature, it seems that we're going to be waiting a bit to agree on the details of it, so @kenellorando and I have agreed to ship this theme without it and put it back on later.

Finally, this pull request includes six commits marking @karenwithakay as co-author, for her role in the design of the features included in those commits. That means that, if I recall correctly, @karenwithakay will now be the third person (after @kenellorando and myself) to have commits attributed to them in the Cadence master branch. Congratulations, @karenwithakay!

### CODE REVIEW

**Comment by Karenwithakay** [comment]
Woo

**Comment by za419** [comment]
I always feel like....

Somebody's Watchin' Me

**Comment by za419** [comment]
Seriously, I didn't think @Karenwithakay would show up so quickly

**Comment by za419** [comment]
Wait, this means that now @Karenwithakay can experience the joy of waiting anxiously for months on end, fixing merge conflicts, to see if @kenellorando has merged the damn pull request yet! Yay!

**Comment by kenellorando** [comment]
- @kenellorando, should we switch the name of it? I dunno, Creepy Cadence sounds boring, but that's probably because I've been using it as an indev name.
Creepy is not a bad name but is acceptable. If you wanted to come up with a name that should be left to the creators, ie you and Karen. 

- Also, should we enable blockMobile? This isn't as bad as space-station, but it's running a lot of CSS animations constantly, it could be a battery drainer.
We will allow it for now and see with our personal usage and testing to see if it is really necessary. Also, most people listening to Cadence on mobile have the browser in the background anyway.

**Comment by kenellorando** [comment]
Please see https://github.com/kenellorando/cadence/pull/105

Too large that resizing does not properly show everything at some screen sizes.. example:
image

Same viewport size with a standard theme:
image

**Comment by kenellorando** [comment]
Mobile scale:
image

**Comment by za419** [comment]
I ran a test on my phone - Leaving `creepy-cadence` open for about an hour, with music playing and the screen on, and Chrome still drained less battery in that time than the idling for the phone call hardware. Looks like my concerns for mobile performance were unwarranted.

**Comment by za419** [comment]
I have @Karenwithakay trying to think of a less conspicuous name

**Pull request merged**
