### PR TITLE
Add tokyo-night theme

### PR DESCRIPTION
**Pull request by za419**
This theme uses the `tokyo-night.gif` image found in old versions of Cadence (actually, that found at the time of the removal of Space Station), uploaded to Imgur to comply with current practice.

See my notes on 45ea882 for a description of the title and subtitle.

The font used for the title and subtitle is the same used in electromaster (and by extension, Star Guardian) - That being "chikara-dzuyoku-b" (found in the 'fonts' folder as `851CHIKARA-DZUYOKU_kanaB.ttf`).

I'm not sure whether @kenellorando would want this theme to be available, but I've always liked it, so now that I remembered the file for it was there I'm submitting a PR to add it.

For reference, on my laptop, `tokyo-night` looks like a less cropped version of this:

image

### CODE REVIEW

**Comment by za419** [comment]
The GIF used for this theme, as referred to in the description, was found [here](https://github.com/kenellorando/cadence/tree/ae4bb13c8356f2243af9d873ad6537f78329e259/public_html/media)

**Comment by za419** [comment]
@kenellorando says that he knows someone who can make sure my subtitle translation (AKA Google's subtitle translation) is good, so for the record we're waiting on that.

**Comment by kenellorando** [comment]
The Google translated version of experience, 経験 ("keiken"), referred to a technically correct but inappropriate translation for the context of Cadence's tagline "A Rhythmic Experience": _the knowledge or skill acquired by experience over a period of time, especially that gained in a particular profession by someone at work._ 

However, to fit the tagline, we needed a translation of experience that referred to a single event ie _an event or occurrence that leaves an impression on someone._ The subtitle words were thus changed to a more appropriate 体験 ("taiken").

**Comment by za419** [comment]
Thanks for finding someone to help with the translation, @kenellorando

**Pull request merged**
